## Put comments here that give an overall description of what your
## functions do

## 
## The following function retrieves a list of functions know as 
## the special "matrix" 
## arguments: x (matrix) The only argument is the matrix to be stored
## return: list of functions tha retrieve or sets the matrix and it's
##         inverse.

makeCacheMatrix <- function(x = matrix()) {
    ## the inv variable stores the inverse matrix.
    inv <- NULL
    ## set: this function sets the value for the matrix, if the 
    ## matrix changed the inv (inverse matrix) variable must be set 
    ## to NULL since is the inverse of the previous matrix.
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    ## get: this function retrieves the x matrix.
    get <- function() x
    ## setInverse: sets the inv variable in the main function scope.
    setInverse <- function(inverse) inv <<- inverse
    ## getInverse: gets the inv variable from the main function scope.
    getInverse <- function() inv
    ## as the last sentence to be evaluated, this list is returned 
    ## by the main function, it provides access to each of the internal
    ## functions defined above.
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## This function caches the solve execution call which is used
## to retrieve the inverse matrix, since this operation is a
## resource expensive one.
## parameter: x a list generated by the function makeCacheMatrix
## returns: inverse  returns the inverse matrix.

cacheSolve <- function(x, ...) {
    ## sets the function variable inverse retrieving the 
    ## inv variable from the makeCacheMatrix function object
    inverse <- x$getInverse()
    ## evaluate the value of the inverse variable
    if(!is.null(inverse)) {
        ## if not null it should print this message
        message("getting cached inverse matrix")
        ## and return the cached inverse matrix
        return(inverse)
    }
    ## if the inverse is null the execution continues
    ## retrieving the x matrix from the makeCacheMatrix 
    ## function object.
    data <- x$get()
    ## Then calculating the inverse with the solve function.
    ## storing the result in the function inverse variable
    inverse <- solve(data, ...)
    ## set the inverse value in the makeCacheMatrix function 
    ## object.
    x$setInverse(inverse)
    ## The function returns the inverse matrix.
    inverse
}
